FROM node:20.14.0 AS builder
COPY ./frontend .
WORKDIR /frontend
RUN npm install
RUN npm run build

FROM nginx:latest
COPY --from=0 ./dist/ /usr/share/nginx/html/
COPY ./frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80